name: CI

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - ".gitignore"
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - ".gitignore"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: gradle
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with gradle
        run: ./gradle build
      - name: Test with gradle
        run: ./gradle test